# Generated by Django 3.1.1 on 2021-03-16 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('CNPJ', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('apelido', models.CharField(blank=True, max_length=200, null=True)),
                ('sexo', models.CharField(choices=[('Masculino', 'M'), ('Feminino', 'F')], max_length=9, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('bi', models.CharField(blank=True, max_length=13, null=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('bairro', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('profissao', models.CharField(blank=True, max_length=250, null=True)),
                ('activo', models.BooleanField(verbose_name='E activo')),
                ('administrador', models.BooleanField(verbose_name='E admnistrador')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conjuge', models.CharField(blank=True, max_length=250, null=True)),
                ('telefoneConjuge', models.CharField(blank=True, max_length=15, null=True)),
                ('dados', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pessoa.pessoa', verbose_name='Dados Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=200, null=True)),
                ('salario', models.FloatField(blank=True, null=True)),
                ('dados', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pessoa.pessoa', verbose_name='Dados Funcionario')),
            ],
        ),
    ]
