# Generated by Django 3.1.1 on 2021-03-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='administrador',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='activo',
            field=models.BooleanField(null=True, verbose_name='E activo'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='administrador',
            field=models.BooleanField(null=True, verbose_name='E admnistrador'),
        ),
    ]
