# Generated by Django 3.1.1 on 2021-03-23 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_auto_20210317_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'get_latest_by': ['id']},
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='dados',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.pessoa', unique=True, verbose_name='Dados Funcionario'),
        ),
    ]
