# Generated by Django 3.1.1 on 2021-03-24 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_auto_20210323_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='dados',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_funcionario', to='pessoa.pessoa', verbose_name='Dados Funcionario'),
        ),
    ]
