# Generated by Django 3.1.1 on 2021-03-24 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0005_auto_20210324_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='dados',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_funcionario', to='pessoa.pessoa', verbose_name='Dados Funcionario'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='bi',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
    ]
